### ISSUE TITLE
Nokia 108 (RM-944) firmware

### ISSUE THREAD

**Issue by milanpeterjani83** [donnm/mtk_fw_tools#9]
I'm trying to unpack the Nokia 108 firmware. I've got Python, ran the script, and it gave me an "alice-py.bin" file. But now, I don't know how to continue this procedure. @donnm How do I install and use a software disassembler? Is it possible to unpack the firmware? (I meant it like to extract a zipped folder, to get access to the files stored inside it.)

**Comment by donnm** [comment]
Hi, sorry, I can't help with that! Good luck!
